#!/bin/bash
# Scipt Name: svnh_concatenate_dumpped_iq.sh
# Description: Concatenate the dumped IQ files for each frame-symbol pair
#              into a single file for each frame-symbol pair. The dumped IQ
#              files are generated by subcarrier-division sensing in Savannah.
# Author: Chung-Hsuan Tung

file_path="../../savannah_isac/files/sensing/"
fft_size=1024
sensing_block_size=128

# Iterate through frame (0-19) and symbol (0-69)
for frame in {0..19}; do
    for sym in {0..69}; do
        # Define the output file for each frame-symbol pair
        output_file="${file_path}sensed_fft_frame${frame}_sym${sym}_sc0_size${fft_size}.bin"

        # Find and sort input files based on the sc ID
        sorted_files=($(ls ${file_path}sensed_fft_frame${frame}_sym${sym}_sc*_size${sensing_block_size}.bin 2>/dev/null | sort -t '_' -k5,5n))

        # Check if we found any files
        if [ ${#sorted_files[@]} -eq 0 ]; then
            echo "Warning: No files found for frame ${frame}, symbol ${sym}"
            continue
        fi

        # Concatenate sorted files into the output file
        cat "${sorted_files[@]}" > "$output_file"

        echo "Merged ${#sorted_files[@]} files into $output_file"
    done
done

echo "All merging operations completed."
